Stores
Abbe-and-Gabbe/jkpgCity pull request #36
Opened 2024-02-24 20:58 UTC by GabrielAdward

2024-03-11 13:51 UTC, albin02forsberg requested changes
Small stuff ;)

2024-03-11 13:51 UTC, albin02forsberg commented on frontend/src/Components/Footer.svelte
> +            <a href="/stores" class="hover:underline me-4 md:me-6">Stores</a>
Should be using `<Link>` tag?

2024-03-13 18:20 UTC, GabrielAdward commented on frontend/src/Components/Footer.svelte
> +            <a href="/stores" class="hover:underline me-4 md:me-6">Stores</a>
Don't think so i googled and looked through our old project, it did not contain any link

2024-03-14 17:34 UTC, GabrielAdward commented
Ready for review!

2024-03-14 18:23 UTC, saleelala approved these changes
LGTM

2024-03-15 10:04 UTC, albin02forsberg approved these changes

2024-03-15 10:05 UTC, merged