homepage
Abbe-and-Gabbe/jkpgCity pull request #37
Opened 2024-02-28 15:04 UTC by saleelala

2024-03-08 09:22 UTC, albin02forsberg requested changes

2024-03-08 09:22 UTC, albin02forsberg commented on frontend/index.html
> +    -->
Remove if not used

2024-03-08 09:22 UTC, albin02forsberg commented on frontend/src/App.svelte
> +<Homepage />
Merge with main before so you can add routing.

2024-03-08 09:22 UTC, albin02forsberg commented on frontend/src/Venues/Homepage.svelte
> +    }
Where is this used?

2024-03-08 09:22 UTC, albin02forsberg commented on frontend/src/Venues/Homepage.svelte
> +    <section class="bg-blue-100 max-w-screen flex flex-wrap items-center justify-between mx-auto p-4 h-auto">
Sections are too big on "Small" screens.

2024-03-08 09:22 UTC, albin02forsberg commented on frontend/src/Venues/img/jkpgcity1.jpg
Move this file to 'src/images/**'

2024-03-17 22:00 UTC, GabrielAdward commented on frontend/src/Components/Navbar.svelte
> +  let isCollapsed = true;
remove line 4-8

2024-03-17 22:01 UTC, GabrielAdward commented on frontend/src/Homepage/Homepage.svelte
> +    <!--SECTION 1-->
Remove all <!-->

2024-03-17 22:12 UTC, GabrielAdward approved these changes
LGTM!

2024-03-17 22:16 UTC, merged